server:
  port: 8088

spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName : com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/jvwarehouse?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username : root
      password : 123456

 # 模板配置
  thymeleaf:
      cache: false # 这个开发配置为false，避免改了模板还要重启服务器
      prefix: classpath:/static/
      suffix: .html              # 下面3个不做解释了，可以不配置
      encoding: UTF-8
      mode: LEGACYHTML5      # 模板的模式

  jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: update
      show-sql: true
  mvc:
    view:
      prefix: classpath:/   # 定位模板的目录
      suffix: .html     # 给返回的页面添加后缀名

